SkeletorHorseProject/SkeletorHorseProject/Controllers/EditSlideShowImagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SkeletorDAL;
using SkeletorDAL.Model;
using System.IO;

namespace SkeletorHorseProject.Controllers
{
    [Authorize]
    public class EditSlideShowImagesController : Controller
    {
        // GET: EditSlideShowImages
        public ActionResult Index()
        {
            var model = Repository.GetAllSlideShowImages();
            return View(model);

        }
        public ActionResult UploadSlideshowFile()
        {

            return View();
        }
        [ChildActionOnly]
        public ActionResult SliderGallery()
        {

            var model = Repository.GetAllSlideShowImages();
            return View(model);
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file)
        {
            try
            {
                if (file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);

                    fileName = fileName.ToLower();

                    if (fileName.EndsWith(".jpg") ||
                        fileName.EndsWith(".png") ||
                        fileName.EndsWith(".bmp") ||
                        fileName.EndsWith(".gif") ||
                        fileName.EndsWith(".jpeg"))
                    {
                        var path = Path.Combine(Server.MapPath("~/SlideImages"), fileName);

                        file.SaveAs(path);
                        path = "~/SlideImages/" + fileName;
                        Repository.AddNewSlideShowFile(fileName, path);
                    }
                    else
                    {
                        ViewBag.Message = "Incorrect file type, please only upload jpg, jpeg, bmp, png or gif";
                        return RedirectToAction("UploadSlideshowFile");
                    }


                }
                ViewBag.Message = "Upload successful";


                return View("UploadSlideshowFile");


            }
            catch
            {
                ViewBag.Message = "Upload failed";
                return RedirectToAction("UploadSlideshowFile");
            }
        }
        public ActionResult DeleteImage(int id, string path)
        {
            string fullPath = Request.MapPath(path);
            if (System.IO.File.Exists(fullPath))
            {
                System.IO.File.Delete(fullPath);
            }
            Repository.DeleteSlideShowImage(id);
            return RedirectToAction("UploadSlideshowFile");
        }

        public ActionResult CropImage(int id, string path)
        {
            return RedirectToAction("UploadSlideshowFile");
        }
    }
}

SkeletorHorseProject/SkeletorHorseProject/Views/EditSlideShowImages/Index.cshtml
@model IEnumerable<SkeletorDAL.Model.SlideShowImgModel>

<body>
    <div class="GalleryWrapper">


        @foreach (var image in Model)
        {



            <div class="GalleryAlineImg">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#@image.ID" style="margin-bottom: 5px;">
                    <img src="@Url.Content(image.ImagePath)" style="margin: -12px; height: 200px; width: 200px;" alt="Image" />
                </button>

                @if (User.Identity.IsAuthenticated && int.Parse(User.Identity.Name) < 2)
                {<p>
                    @Html.ActionLink("Delete image", "DeleteImage", "EditSlideShowImages", new { id = image.ID, path = image.ImagePath }, new { onclick = "return confirm('Are you sure you wish to delete this article?');" })
                </p>
                }

                <div id="@image.ID" class="modal fade" tabindex="-1">
                    <div id="lightbox" class="modal-dialog">
                        <div class="modal-content; col-md-12; span9 centred" style="max-width: 3000px">
                            <img src="@Url.Content(image.ImagePath)" class="img-responsive; img-responsive center-block" />
                        </div>
                    </div>
                </div>
            </div>



        }



    </div>
</body>

SkeletorHorseProject/SkeletorHorseProject/Views/EditSlideShowImages/SliderGallery.cshtml
@model IEnumerable<SkeletorDAL.Model.ImageModel>

    @{
        Layout = null;
    }


<script src="~/Scripts/slideshow.size.js"></script>
<body>
        <div class="GalleryWrapper">
            @foreach (var image in Model)
            {
                <div class="GalleryAlineImg">
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#@image.ID" style="margin-bottom: 5px;">
                        <img src="@Url.Content(image.ImagePath)" style="margin: -12px; height: 200px; width: 200px;" alt="Image" />
                    </button>
                    @if (User.Identity.IsAuthenticated && int.Parse(User.Identity.Name) < 2)
                    {                    
                        <div class="overlay">
                            <div class="overlay-inner">
                                <p>
                                    @Html.ActionLink("Delete image", "DeleteImage", "EditSlideShowImages", new {id = image.ID, path = image.ImagePath}, new {onclick = "return confirm('Are you sure you wish to delete this article?');"})
                                </p>
                            </div>
                        </div>
                    }
                    <div id="@image.ID" class="modal fade" tabindex="-1">
                        <div id="lightbox" class="modal-dialog">
                            <div class="modal-content; col-md-12; span9 centred" style="max-width: 3000px">
                                <img src="@Url.Content(image.ImagePath)" class="img-responsive; img-responsive center-block" />
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </body>

SkeletorHorseProject/SkeletorHorseProject/Views/EditSlideShowImages/UploadSlideshowFile.cshtml
@model IEnumerable<SkeletorDAL.Model.ImageModel>

@using (Html.BeginForm("Upload", "EditSlideShowImages", FormMethod.Post, new { enctype = "multipart/form-data" }))
{ @Html.AntiForgeryToken()
    <fieldset>
        <legend>Upload a file</legend>
        <p>Only .jpg .jpeg . png and .gif allowed</p>
        <div class="editor-field"> @Html.TextBox("file", "", new { type = "file" }) </div>
        <div class="editor-field"> <input type="submit" value="Upload" /> </div>
    </fieldset> 
}

@Html.Action("SliderGallery")