SkeletorHorseProject/SkeletorHorseProject/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SkeletorHorseProject.Models;
using SkeletorDAL;
using SkeletorDAL.Model;
namespace SkeletorHorseProject.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            var model = Repository.AboutReadOnly();
            return View(model);
        }


    }
}

SkeletorHorseProject/SkeletorHorseProject/Controllers/EditAboutPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls.WebParts;
using SkeletorDAL;
using SkeletorDAL.Model;

namespace SkeletorHorseProject.Controllers
{
    [Authorize]
	public class EditAboutPageController : Controller
	{
		// GET: EditAboutPage
		public ActionResult EditAbout()
		{
			var currentAboutInfo = Repository.GetLatestAboutInformation();
			return View(currentAboutInfo);
		}
		[HttpPost]
		public ActionResult EditAbout(EditAboutModel model)
		{
			if (ModelState.IsValid)
			{
				var about = Repository.GetLatestAbout();
				Repository.UpdateAbouts(Repository.SetAboutValues(model, about));
				return RedirectToAction("Index", "About");
			}
			return View(model);
		}
	}
}

SkeletorHorseProject/SkeletorHorseProject/Views/About/Index.cshtml
@model SkeletorDAL.Model.AboutReadOnlyModel
@using SkeletorHorseProject.Models

<p>
	@if (User.Identity.IsAuthenticated && int.Parse(User.Identity.Name) < 2)
	{
		@Html.ActionLink("Edit", "EditAbout", "EditAboutPage")
	}
</p>

<div class="AboutContent">
    <div class="AboutInfoBox">
        <h1>@Model.Header1</h1>
        <p>@Model.Textfield1</p>
        <hr/>
    </div>

    <div class="AboutInfoBox">
        <h1>@Model.Header2</h1>
        <p>@Model.Textfield2</p>
        <hr />
    </div>

    <div class="AboutInfoBox">
        <h1>@Model.Header3</h1>
        <p>@Model.Textfield3</p>
    </div>
</div>