SkeletorHorseProject/SkeletorHorseProject/Controllers/AdminLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using SkeletorDAL;
using SkeletorHorseProject.Helpers;
using SkeletorHorseProject.Models;

namespace SkeletorHorseProject.Controllers
{
    public class AdminLoginController : Controller
    {
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(AdminLoginModel model)
        {

            if (ModelState.IsValid)
            {
                bool isValid = Repository.AuthenticateAdminLogin(model.Username,model.Password.SuperHash());
                if (isValid)
                {

                    FormsAuthentication.SetAuthCookie(Repository.GetAdminId(model.Username).ToString(),false);
                   
                    return RedirectToAction("Index","Home");
                }
                else
                {
                    return View(model);                    
                }
                }
            else
            {
                return View(model);
            }
        }
    }
}

SkeletorHorseProject/SkeletorHorseProject/Controllers/CreateHorseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SkeletorDAL;
using SkeletorDAL.Model;
using SkeletorDAL.POCO;

namespace SkeletorHorseProject.Controllers
{
    [Authorize]
	public class CreateHorseController : Controller
	{
		// GET: CreateHorse

		public ActionResult CreateHorse()
		{
			return View();
		}
		[HttpPost]
		public ActionResult CreateHorse(CreateHorseModel model)
		{


			@TempData["CheckboxError"] = "The fields 'For sale' and 'Sold' can't both be checked";
			if (ModelState.IsValid && (model.IsForSale == true && model.IsSold == false) || (model.IsForSale == false && model.IsSold == true) || (model.IsForSale == false && model.IsSold == false))
			{
				TempData["CheckboxError"] = string.Empty;

				Repository.AddHorse(model);
				return RedirectToAction("Index", "Home");
			}
			return View(model);
		}
	}
}

SkeletorHorseProject/SkeletorHorseProject/Controllers/ManageAdminsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SkeletorDAL.Model;
using SkeletorDAL;

namespace SkeletorHorseProject.Controllers
{
    [Authorize]
    public class ManageAdminsController : Controller
    {
        // GET: ManageAdmins
        public ActionResult Index()
        {
            
            return View(Repository.GetAllAdmins());
        }

        public ActionResult Delete(int id)
        {
            try
            {
                Repository.RemoveAdminByID(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }
        public ActionResult Edit(int id)
        {
            var admin = Repository.GetAdminInformationForEditModel(id);
            return View(admin);
        }
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Edit(int id, EditAdminModel model)
        {
            if (ModelState.IsValid)
            {
                Repository.UpdateAdminProfile(id, model);
                return RedirectToAction("Index");
            }
            return View(model);
        }


    }
}

SkeletorHorseProject/SkeletorHorseProject/Controllers/RegisterAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SkeletorDAL;
using SkeletorDAL.Model;

namespace SkeletorHorseProject.Controllers
{

    [Authorize]
    public class RegisterAdminController : Controller
    {
        // GET: RegisterAdmin
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Register(RegisterAdminModel model)
        {
            if (ModelState.IsValid)
            {
                Repository.RegisterAdmin(model);
                ModelState.Clear();
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
    }
}

SkeletorHorseProject/SkeletorHorseProject/Views/AdminLogin/Index.cshtml
<h2>Redirect to start page</h2>

SkeletorHorseProject/SkeletorHorseProject/Views/AdminLogin/Login.cshtml
@using SkeletorDAL
@model SkeletorHorseProject.Models.AdminLoginModel
@{
    ViewBag.Title = "Login";
}

<div>

    @using (Html.BeginForm("Login", "AdminLogin", FormMethod.Post))
    {
        <div>
            @if (!User.Identity.IsAuthenticated)
            {


                <br />
                <div>
                    @Html.LabelFor(m => m.Username)
                    @Html.TextBoxFor(m => m.Username)
                    @Html.ValidationMessageFor(m => m.Username, "")

                </div>
                @Html.AntiForgeryToken()
                <div>
                    @Html.LabelFor(m => m.Password)
                    @Html.PasswordFor(m => m.Password)
                    @Html.ValidationMessageFor(m => m.Password, "")



                </div>
                <div>
                    <input type="submit" value="Login" />
                </div>
            }
        </div>
    }
    
    @if(User.Identity.IsAuthenticated && int.Parse(User.Identity.Name) == 1)
    {
       @Html.ActionLink("Register New Admin","Register","RegisterAdmin");
        <br />
        @Html.ActionLink("Manage All Admins", "Index", "ManageAdmins");
	    <br />
		@Html.ActionLink("Add New Horse", "CreateHorse", "CreateHorse");
		
    }
</div>